import { Item, ItemRarity } from '@/types/character';
import { EnemyData, LootData } from '@/types/game';

// Loot generation based on enemy and player level
export interface LootGenerationParams {
  enemy: EnemyData;
  playerLevel: number;
  playerClass: string;
  difficulty: 'easy' | 'medium' | 'hard' | 'deadly';
}

// Rarity weights based on enemy level
function getRarityWeights(enemyLevel: number): Record<ItemRarity, number> {
  if (enemyLevel <= 2) {
    return {
      Common: 70,
      Uncommon: 25,
      Rare: 5,
      'Very Rare': 0,
      Legendary: 0,
      Artifact: 0,
    };
  } else if (enemyLevel <= 5) {
    return {
      Common: 50,
      Uncommon: 35,
      Rare: 12,
      'Very Rare': 3,
      Legendary: 0,
      Artifact: 0,
    };
  } else if (enemyLevel <= 10) {
    return {
      Common: 30,
      Uncommon: 40,
      Rare: 20,
      'Very Rare': 8,
      Legendary: 2,
      Artifact: 0,
    };
  } else {
    return {
      Common: 15,
      Uncommon: 30,
      Rare: 30,
      'Very Rare': 18,
      Legendary: 6,
      Artifact: 1,
    };
  }
}

export function generateLootRarity(enemyLevel: number): ItemRarity {
  const weights = getRarityWeights(enemyLevel);
  const totalWeight = Object.values(weights).reduce((sum, w) => sum + w, 0);
  let random = Math.random() * totalWeight;

  for (const [rarity, weight] of Object.entries(weights)) {
    random -= weight;
    if (random <= 0) {
      return rarity as ItemRarity;
    }
  }

  return 'Common'; // Fallback
}

// Class-appropriate item types
const classItemPreferences: Record<string, string[]> = {
  Fighter: ['weapon', 'armor', 'shield'],
  Paladin: ['weapon', 'armor', 'shield'],
  Ranger: ['weapon', 'armor', 'bow'],
  Rogue: ['weapon', 'armor', 'dagger'],
  Barbarian: ['weapon', 'armor'],
  Monk: ['weapon', 'armor'],
  Wizard: ['weapon', 'staff', 'robe'],
  Sorcerer: ['weapon', 'staff', 'robe'],
  Warlock: ['weapon', 'staff', 'robe'],
  Cleric: ['weapon', 'armor', 'shield', 'holy symbol'],
  Druid: ['weapon', 'armor', 'staff'],
  Bard: ['weapon', 'armor', 'instrument'],
  Artificer: ['weapon', 'armor', 'tool'],
};

export function generateLootItem(
  params: LootGenerationParams
): LootData {
  const rarity = generateLootRarity(params.enemy.level);
  const classPrefs = classItemPreferences[params.playerClass] || ['weapon', 'armor'];
  const itemType = classPrefs[Math.floor(Math.random() * classPrefs.length)];
  
  // Generate item name based on rarity and type
  const itemName = generateItemName(itemType, rarity, params.enemy.name);
  
  return {
    itemId: `loot-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
    name: itemName,
    rarity,
    imageUrl: undefined, // Will be generated by AI
  };
}

function generateItemName(
  type: string,
  rarity: ItemRarity,
  enemyName: string
): string {
  const rarityPrefixes: Record<ItemRarity, string[]> = {
    Common: ['Rusty', 'Worn', 'Simple', 'Basic'],
    Uncommon: ['Fine', 'Polished', 'Well-crafted', 'Sturdy'],
    Rare: ['Masterwork', 'Enchanted', 'Superior', 'Exquisite'],
    'Very Rare': ['Legendary', 'Mythic', 'Ancient', 'Powerful'],
    Legendary: ['Divine', 'Eternal', 'Transcendent', 'God-forged'],
    Artifact: ['Primordial', 'World-shattering', 'Reality-bending', 'Infinite'],
  };

  const prefixes = rarityPrefixes[rarity];
  const prefix = prefixes[Math.floor(Math.random() * prefixes.length)];
  
  const typeNames: Record<string, string[]> = {
    weapon: ['Sword', 'Blade', 'Axe', 'Mace', 'Dagger'],
    armor: ['Armor', 'Mail', 'Plate', 'Leather'],
    shield: ['Shield', 'Buckler', 'Aegis'],
    staff: ['Staff', 'Rod', 'Wand'],
    robe: ['Robe', 'Vestments', 'Cloak'],
    bow: ['Bow', 'Longbow', 'Crossbow'],
    instrument: ['Lute', 'Harp', 'Flute'],
    tool: ['Tool', 'Device', 'Apparatus'],
  };

  const typeNamesList = typeNames[type] || [type];
  const typeName = typeNamesList[Math.floor(Math.random() * typeNamesList.length)];
  
  return `${prefix} ${typeName}${rarity !== 'Common' ? ` of ${enemyName}` : ''}`;
}

// Generate multiple loot items
export function generateLoot(
  params: LootGenerationParams,
  count: number = 1
): LootData[] {
  const loot: LootData[] = [];
  
  for (let i = 0; i < count; i++) {
    // Chance to drop loot based on difficulty
    const dropChance: Record<string, number> = {
      easy: 0.3,
      medium: 0.5,
      hard: 0.7,
      deadly: 0.9,
    };
    
    if (Math.random() < dropChance[params.difficulty]) {
      loot.push(generateLootItem(params));
    }
  }
  
  return loot;
}














